//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.17 at 11:31:58 AM EET 
//


package org.backend2.core.xml.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.backend2.core.xml.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Comment_QNAME = new QName("", "comment");
    private final static QName _Table_QNAME = new QName("", "table");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.backend2.core.xml.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TableXml }
     * 
     */
    public TableXml createTableXml() {
        return new TableXml();
    }

    /**
     * Create an instance of {@link IndexColumnXml }
     * 
     */
    public IndexColumnXml createIndexColumnXml() {
        return new IndexColumnXml();
    }

    /**
     * Create an instance of {@link PropertyXml }
     * 
     */
    public PropertyXml createPropertyXml() {
        return new PropertyXml();
    }

    /**
     * Create an instance of {@link ColumnXml }
     * 
     */
    public ColumnXml createColumnXml() {
        return new ColumnXml();
    }

    /**
     * Create an instance of {@link PropertiesXml }
     * 
     */
    public PropertiesXml createPropertiesXml() {
        return new PropertiesXml();
    }

    /**
     * Create an instance of {@link IndexesXml }
     * 
     */
    public IndexesXml createIndexesXml() {
        return new IndexesXml();
    }

    /**
     * Create an instance of {@link EntityXml }
     * 
     */
    public EntityXml createEntityXml() {
        return new EntityXml();
    }

    /**
     * Create an instance of {@link ColumnsXml }
     * 
     */
    public ColumnsXml createColumnsXml() {
        return new ColumnsXml();
    }

    /**
     * Create an instance of {@link IndexXml }
     * 
     */
    public IndexXml createIndexXml() {
        return new IndexXml();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TableXml }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "table")
    public JAXBElement<TableXml> createTable(TableXml value) {
        return new JAXBElement<TableXml>(_Table_QNAME, TableXml.class, null, value);
    }

}
